### ISSUE TITLE
CUDA_ERROR _OUT_OF_MEMORY error during training

### ISSUE THREAD

**Issue by qiqigit** [HugoBA92/PBNS#13]
Hi, @hbertiche , thank you for sharing this interesting work!
I am trying to train the resizer model with your sample outfit. Following the instructions indicated in the following issue, I am using LossRay.py instead of Loss.py.
https://github.com/hbertiche/PBNS/issues/4#issue-1210440340

Then I ran into endless errors as follow.  Any help is appreciated! (For your information, ray 1.12.1 is used. )
(_nn pid=19780) 2022-12-12 22:06:16.930196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 21235 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=17180) 2022-12-12 22:06:18.957119: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 7164 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=18084) 2022-12-12 22:06:18.968304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 7164 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=20536) 2022-12-12 22:06:18.907544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 21668 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=21472) 2022-12-12 22:06:18.941771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 7164 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=17552) 2022-12-12 22:06:18.963800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 7164 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=16320) 2022-12-12 22:06:19.211718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 7132 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=21780) 2022-12-12 22:06:19.243256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 7132 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=4028) 2022-12-12 22:06:19.352253: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
7132 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=20516) 2022-12-12 22:06:21.690484: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 7108 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=22412) 2022-12-12 22:06:25.260554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 7094 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=12248) 2022-12-12 22:06:25.241457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 7094 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=22888) 2022-12-12 22:06:26.281948: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 7094 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=19796) 2022-12-12 22:06:34.669805: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 7085 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=13548) 2022-12-12 22:06:42.790054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
 7037 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=3848) 2022-12-12 22:06:47.407290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with
7012 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:08:00.0, compute capability: 8.6
(_nn pid=16320) 2022-12-12 22:06:54.888554: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 6.96G (7479134208 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=19780) 1 Physical GPUs, 1 Logical GPU
(_nn pid=21472) 2022-12-12 22:06:56.062964: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 7.00G (7512688640 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=21780) 2022-12-12 22:06:56.237588: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 6.96G (7479134208 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=17552) 2022-12-12 22:06:59.508442: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 7.00G (7512688640 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=17180) 2022-12-12 22:06:59.520325: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 7.00G (7512688640 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=18084) 2022-12-12 22:07:00.784483: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 7.00G (7512688640 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=4028) 2022-12-12 22:07:01.025600: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 6.96G (7479134208 bytes) from device: CUDA_ERROR_
OUT_OF_MEMORY: out of memory
(_nn pid=16320) 2022-12-12 22:07:03.546387: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 6.27G (6731220480 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=18084) 2022-12-12 22:07:04.234943: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 6.30G (6761419776 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=16320) 2022-12-12 22:07:05.020442: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 5.64G (6058098176 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=21472) 2022-12-12 22:07:07.655235: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 6.30G (6761419776 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=17180) 2022-12-12 22:07:10.384186: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 6.30G (6761419776 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=17552) 2022-12-12 22:07:10.312539: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 6.30G (6761419776 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=4028) 2022-12-12 22:07:12.649814: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 6.27G (6731220480 bytes) from device: CUDA_ERROR_
OUT_OF_MEMORY: out of memory
(_nn pid=20536) 2022-12-12 22:07:13.652236: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 21.16G (22720544768 bytes) from device: CUDA_ERR
OR_OUT_OF_MEMORY: out of memory
(_nn pid=21780) 2022-12-12 22:07:18.196147: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 6.27G (6731220480 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=16320) 2022-12-12 22:07:20.345179: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 5.08G (5452288000 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=20536) 2022-12-12 22:07:23.417926: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 19.04G (20448489472 bytes) from device: CUDA_ERR
OR_OUT_OF_MEMORY: out of memory
(_nn pid=17180) 2022-12-12 22:07:23.870578: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 5.67G (6085277696 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=21472) 2022-12-12 22:07:24.306200: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 5.67G (6085277696 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=17552) 2022-12-12 22:07:24.588072: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 5.67G (6085277696 bytes) from device: CUDA_ERROR
_OUT_OF_MEMORY: out of memory
(_nn pid=4028) 2022-12-12 22:07:24.550447: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 5.64G (6058098176 bytes) from device: CUDA_ERROR_
OUT_OF_MEMORY: out of memory

**Comment by hbertiche** [comment]
which OS are you using?
I ran into a similar problem with 'ray' module as well, but only when I use windows,
I do not know why this happens yet

**Comment by qiqigit** [comment]
> which OS are you using? I ran into a similar problem with 'ray' module as well, but only when I use windows, I do not know why this happens yet

Thanks for getting back! Yes, I am running this on windows 10.

**Comment by qiqigit** [comment]
Hi, @hbertiche  I ran this project on Ubuntu 22.04 but came across the CUDA_ERROR_NO_DEVICE error.
Which version of the ray library did you use?

**Comment by hbertiche** [comment]
I tested this in Ubuntu 20.04 and ray version 1.12 with no issue,
I am still unable to identify the problem,

there may be a workaround if you are willing to look into the code and change stuff,
collision detection is done using 'scipy.spatial.cKDTree', constructing a tree for the posed boody and querying cloth vertices against it,
the modification I propose is as follows,
given a batch of N samples as N bodies {B1, B2, ..., BN} and N outfits O1, O2, ..., ON}, both represented as meshes (V: vertices, F: faces),
merge all bodies into a single body mesh, and do the same for the outfit,
to avoid collisions between different samples within the batch (B1 collides with O4, this would be wrong!), add an offset to each body and outfit of the batch, example: for the 'i'-th sample of the batch Bi.V += (i * offset, 0, 0) and Oi.V += (i * offset, 0, 0),
'offset' should be chosen such that it ensures there will not be matchings between different samples, 2-3 meters might be enough, 5 meters to be sure (this might also depend on the size of your human and outfit), also, the example I wrote distributes samples across the x-axis, you could spread them in the XY-plane or even the whole XYZ-volume, it should not matter, just make sure there will not be collisions between different samples!!
if you do it like this, the method 'cKDTree.query' can run queries in parallel (see argument 'n_jobs'),
I have not tested this myself, so I do not know if it will work as intended and how much would performance increase,

also this would require some engineering efforts to adapt the rest of the collision loss,

do this in "Losses.py", that does not use Ray library, then the issue with this library won't appear
