### ISSUE TITLE
where is the preprocess.py 

### ISSUE THREAD

**Issue by wtupdl** [HugoBA92/PBNS#15]
Hello, I want to know where is the preprocess.py mentioned in the comment of PBNS\Data\smpl\smpl_np.py

**Comment by dancasas** [comment]
Not sure if this helps, but check out this answer. You can get the `preprocess.py` from another repo:

https://github.com/hbertiche/PBNS/issues/5#issuecomment-1150291468

**Comment by wtupdl** [comment]
ok，thank you

**Comment by hbertiche** [comment]
Hi,

It is as @dancasas says (thanks btw!),
the original SMPL model, provided as .pkl files, required some pre-processing to be usable in python3,
you can find the _preprocess.py_ script in https://github.com/CalciferZh/SMPL
