### ISSUE TITLE
Pose Database

### ISSUE THREAD

**Issue by moranli-aca** [HugoBA92/PBNS#16]
Can you provide the pose data processing scripts for CMU MoCap pose as described in the Sect.4.3 "Pose database" of your main paper?

Currently, I want to reproduce the results reported in your main paper and want to achieve a fair comparison with the quantitative results in Table2. of the main paper.

**Comment by hbertiche** [comment]
sure!

before running the script, follow these steps:
1-Gather all CMU pose squences
2-Randomly split sequences as _85%/15%_ for train and test
3-Save the training sequences (after split) in a big array with shape `N x 72` as _"cmu_poses_train.npy"_

Then, the script I used is as follows
```
from random import shuffle
import numpy as np

def dist(p0, p1):
	return np.max(np.abs(p0[3:] - p1[3:]))

N = 3000
thr = .5

P = np.load('cmu_poses_train.npy')

# shuffle
idx = list(range(len(P)))
shuffle(idx)
P = P[idx]

# downsample to ~10%
P = P[::10]

# subsample
S = [P[0]]
for i,p in enumerate(P):
	print(len(S), i, len(P))
	d = [dist(p, s) for s in S]
	if min(d) < thr: continue
	S += [p]
	if len(S) > N: break


S = np.array(S)

# shuffle again
idx = list(range(S.shape[0]))
shuffle(idx)
S = S[idx]

# train/validation
M = int(.85 * S.shape[0])
np.save('train.npy', S[:M])
np.save('validation.npy', S[M:])
```

this will ensure any pair of poses has a difference of at least `0.5 rad`, and then create two splits, _train_ and _validation_, used to train the network,

this process also ensures that the _test_ split (generated in the steps before running the script) consists of completely unseen pose sequences, this split is the one used to generate all the results shown in the paper and video,

also note there is randomness in this process, and thus, your results might differ slightly from mine
