### ISSUE TITLE
The experimental results are strange

### ISSUE THREAD

**Issue by wtupdl** [HugoBA92/PBNS#17]
Can you tell me the source of the data set you use? I use the CMU data set to read the pose data of its npz file and convert it into an n*72 data format, and then use the script you provided for data processing and training for 10 times After the final body and clothing animations have very strange distortions 。My data comes from https://amass.is.tue.mpg.de/download.php like the data of SNUG

**Comment by wtupdl** [comment]
How to convert the n*156 data of the CMU dataset into n*72? My processing is to do a simple split on the data, but the result is very bad

**Comment by hbertiche** [comment]
SMPL model has been extended to more complete models (SMPL-X, SMPL-H, ...), thus the current data has a higher dimensionality (156 vs 72),

when I made this work (PBNS), the dataset provided was compatible with SMPL, and thus I did not face such issues, because of this, I am afraid I cannot be of much help in this regard,
I recommend contacting the authors of SMPL to ask for advice on how to do this

**Comment by wtupdl** [comment]
So the pose data you downloaded at that time was n*72, instead of reducing the data of n*156 to n*72, right?

**Comment by hbertiche** [comment]
yes, that is correct!

**Comment by wtupdl** [comment]
ok，Can you provide your data download address? I use AIST++ for training. It may be because the human body movements in the data set are too complicated, so the effect is not ideal.

**Comment by hbertiche** [comment]
I checked the CMU dataset from https://amass.is.tue.mpg.de/download.php and while the data is given as `N x 156`, I observed that it is possible to just drop everything past `72` dimensions, like `X = X[..., : 72]`, and get SMPL compatible pose arrays
have you tried this? did this not work for you?
![image](https://user-images.githubusercontent.com/16307925/225097520-afbb65fa-f6a8-41f2-b72e-d4cba8c646da.png)
(the hand looks weird though)

originally, the CMU data I used came from this project http://mocap.cs.cmu.edu/
but it requires some adaptation to work with SMPL, which is what the authors of https://www.di.ens.fr/willow/research/surreal/ did,
I think you might be able to download SURREAL dataset and get the pose data from there, if you wanted to,
but I am confident this pose data is likely the same as the one within AMASS dataset (https://amass.is.tue.mpg.de/download.php)

please note all of this was few years ago and I do not recall properly, so some details might be off

**Comment by wtupdl** [comment]
ok,thank you

**Comment by wtupdl** [comment]
I successfully solved my problem and got great experimental results because I was using the wrong SMPL model. Thank you for your patience and help, and I am sorry for the trouble you caused.

**Comment by hbertiche** [comment]
do not worry at all!

I hope I was helpful,
do not hesitate to ask further questions

**Comment by wtupdl** [comment]
ok thank you, I read PBNS and SNUG, and found this kind of clothing training using self-supervision very interesting, can you recommend some papers of the same type
