### ISSUE TITLE
can you recommend some papers of the same type

### ISSUE THREAD

**Issue by wtupdl** [HugoBA92/PBNS#18]
Thanks for sharing such interesting work, I read PBNS and SNUG and found this kind of clothing training using self-supervision very interesting, can you recommend some papers of the same type?

**Comment by hbertiche** [comment]
sure!

I recently published _Neural Cloth Simulation_ in SIGGRAPH Asia 2022
Here is the site:
https://hbertiche.github.io/NeuralClothSim/
It is built on top of PBNS as a more complete solution to the garment animation problem with physics.

Also, very recently, a new CVPR paper has been published on this topic, _HOOD: Hierarchical Graphs for Generalized Modelling of Clothing Dynamics_, which seems very promising. Their approach also follows a self-supervised training scheme, but using a model able to generalize to different garments.
Here is the site:
https://dolorousrtur.github.io/hood/

**Comment by wtupdl** [comment]
ok,thank you

**Comment by MRYQY** [comment]
Dear author, your coding is very good but I can not find the document "Data/train.npy" to run, can you tell me how generate the document, thank you
