### ISSUE TITLE
Training with custom data

### ISSUE THREAD

**Issue by SeanHoang2203** [HugoBA92/PBNS#19]
Hi,

Thanks for your amazing work and publishing your code. It's really inspiring. I'm having some issues when trying to train with custom body and outfit. 

My first question is does this work with other rest pose? Or the rest pose are strictly fixed? I noticed that when I changed the rest pose and re-generate the body mesh using this `G, B = smpl.set_params(rest_pose, beta=model._shape, with_body=True)` (with `model._shape` being my own SMPL betas) I obtained a translated model from the original. 
![image](https://github.com/hbertiche/PBNS/assets/43663861/6fa55780-4f2a-4055-b77d-a0318eae0db9)

As a workaround, I manually translate my outfit to where the re-generated body is for alignment. I can train PBNS with this (custom rest pose, custom data) but not having good results. So does this relate to the rest pose somehow? For ref, my pose compares to original rest pose
![image](https://github.com/hbertiche/PBNS/assets/43663861/99963c57-6a11-4a80-815f-168034d2e8fe)

Another question is how good must the alignment of the outfit and the body be? Is any interpenetration allowed? 
The same can be asked for the outfit also since my outfit (t-shirt + skirt) is having some interpenetration.
![image](https://github.com/hbertiche/PBNS/assets/43663861/1c663802-5e92-4783-a3f0-a740b10abed1)

I hope my questions are clear and thanks again for the work.

**Comment by hbertiche** [comment]
The rest pose is fixed, but it should be possible to adapt the code to work with arbitrary rest poses.
Small interpenetrations in the rest pose like the ones you show are OK.
